/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ConversationId = IDL.Nat;
export const MessageId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'text' : IDL.Text,
  'sentAt' : Timestamp,
  'conversationId' : ConversationId,
  'senderId' : UserId,
});
export const UserInfo = IDL.Record({
  'id' : UserId,
  'nickname' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
});
export const ConversationSummary = IDL.Record({
  'id' : ConversationId,
  'otherUserId' : UserId,
  'lastActivityAt' : Timestamp,
  'otherUserNickname' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'getMessages' : IDL.Func(
      [IDL.Text, ConversationId],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMessagesSince' : IDL.Func(
      [IDL.Text, ConversationId, Timestamp],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserInfo)], ['query']),
  'getUserById' : IDL.Func([UserId], [IDL.Opt(UserInfo)], ['query']),
  'listConversations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ConversationSummary)],
      ['query'],
    ),
  'registerUser' : IDL.Func([IDL.Text], [UserId], []),
  'sendMessage' : IDL.Func(
      [IDL.Text, ConversationId, IDL.Text],
      [IDL.Opt(MessageId)],
      [],
    ),
  'setNickname' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'startConversation' : IDL.Func(
      [IDL.Text, UserId],
      [IDL.Opt(ConversationId)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ConversationId = IDL.Nat;
  const MessageId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'text' : IDL.Text,
    'sentAt' : Timestamp,
    'conversationId' : ConversationId,
    'senderId' : UserId,
  });
  const UserInfo = IDL.Record({
    'id' : UserId,
    'nickname' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
  });
  const ConversationSummary = IDL.Record({
    'id' : ConversationId,
    'otherUserId' : UserId,
    'lastActivityAt' : Timestamp,
    'otherUserNickname' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'getMessages' : IDL.Func(
        [IDL.Text, ConversationId],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMessagesSince' : IDL.Func(
        [IDL.Text, ConversationId, Timestamp],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserInfo)], ['query']),
    'getUserById' : IDL.Func([UserId], [IDL.Opt(UserInfo)], ['query']),
    'listConversations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'registerUser' : IDL.Func([IDL.Text], [UserId], []),
    'sendMessage' : IDL.Func(
        [IDL.Text, ConversationId, IDL.Text],
        [IDL.Opt(MessageId)],
        [],
      ),
    'setNickname' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'startConversation' : IDL.Func(
        [IDL.Text, UserId],
        [IDL.Opt(ConversationId)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };