/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ConversationId = bigint;
export interface ConversationSummary {
  'id' : ConversationId,
  'otherUserId' : UserId,
  'lastActivityAt' : Timestamp,
  'otherUserNickname' : [] | [string],
}
export interface Message {
  'id' : MessageId,
  'text' : string,
  'sentAt' : Timestamp,
  'conversationId' : ConversationId,
  'senderId' : UserId,
}
export type MessageId = bigint;
export type Timestamp = bigint;
export type UserId = bigint;
export interface UserInfo {
  'id' : UserId,
  'nickname' : [] | [string],
  'createdAt' : Timestamp,
}
export interface _SERVICE {
  'getMessages' : ActorMethod<[string, ConversationId], Array<Message>>,
  'getMessagesSince' : ActorMethod<
    [string, ConversationId, Timestamp],
    Array<Message>
  >,
  'getMyProfile' : ActorMethod<[string], [] | [UserInfo]>,
  'getUserById' : ActorMethod<[UserId], [] | [UserInfo]>,
  'listConversations' : ActorMethod<[string], Array<ConversationSummary>>,
  'registerUser' : ActorMethod<[string], UserId>,
  'sendMessage' : ActorMethod<
    [string, ConversationId, string],
    [] | [MessageId]
  >,
  'setNickname' : ActorMethod<[string, [] | [string]], undefined>,
  'startConversation' : ActorMethod<[string, UserId], [] | [ConversationId]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];